-- Enable RLS on projects table
ALTER TABLE projects ENABLE ROW LEVEL SECURITY;

-- Public can read all projects
CREATE POLICY "Public read access"
  ON projects FOR SELECT
  USING (true);

-- Only authenticated admin can insert
CREATE POLICY "Admin insert"
  ON projects FOR INSERT
  TO authenticated
  WITH CHECK (auth.jwt() ->> 'email' = current_setting('app.admin_email', true));

-- Only authenticated admin can update
CREATE POLICY "Admin update"
  ON projects FOR UPDATE
  TO authenticated
  USING (auth.jwt() ->> 'email' = current_setting('app.admin_email', true))
  WITH CHECK (auth.jwt() ->> 'email' = current_setting('app.admin_email', true));

-- Only authenticated admin can delete
CREATE POLICY "Admin delete"
  ON projects FOR DELETE
  TO authenticated
  USING (auth.jwt() ->> 'email' = current_setting('app.admin_email', true));

-- ============================================================
-- IMPORTANT: Jalankan ini di Supabase SQL Editor.
--
-- Setelah itu, set admin email di Supabase Dashboard:
--   Settings → Database → Configuration → "app.admin_email"
--
-- ATAU gunakan pendekatan lebih simpel di bawah ini
-- yang hardcode email langsung (ganti dengan email Anda):
-- ============================================================

-- ALTERNATIF SIMPEL (uncomment dan ganti email):
--
-- DROP POLICY IF EXISTS "Admin insert" ON projects;
-- DROP POLICY IF EXISTS "Admin update" ON projects;
-- DROP POLICY IF EXISTS "Admin delete" ON projects;
--
-- CREATE POLICY "Admin insert" ON projects FOR INSERT
--   TO authenticated WITH CHECK (auth.uid() IN (
--     SELECT id FROM auth.users WHERE email = 'YOUR_EMAIL@gmail.com'
--   ));
--
-- CREATE POLICY "Admin update" ON projects FOR UPDATE
--   TO authenticated
--   USING (auth.uid() IN (SELECT id FROM auth.users WHERE email = 'YOUR_EMAIL@gmail.com'))
--   WITH CHECK (auth.uid() IN (SELECT id FROM auth.users WHERE email = 'YOUR_EMAIL@gmail.com'));
--
-- CREATE POLICY "Admin delete" ON projects FOR DELETE
--   TO authenticated
--   USING (auth.uid() IN (SELECT id FROM auth.users WHERE email = 'YOUR_EMAIL@gmail.com'));


-- ============================================================
-- NEW: SKILLS TABLE
-- ============================================================
CREATE TABLE IF NOT EXISTS skills (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  icon_name text NOT NULL,
  color_class text NOT NULL DEFAULT 'text-zinc-500',
  order_index integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security (RLS)
ALTER TABLE skills ENABLE ROW LEVEL SECURITY;

-- Allow public read access
CREATE POLICY "Public read access" ON skills FOR SELECT USING (true);

-- Allow authenticated users (admin) to modify
CREATE POLICY "Admin insert" ON skills FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Admin update" ON skills FOR UPDATE TO authenticated USING (true);
CREATE POLICY "Admin delete" ON skills FOR DELETE TO authenticated USING (true);
